[api]
    dashboard = true

[entryPoints]
    [entryPoints.web]
        address = ":80"
        [entryPoints.web.redirections.entryPoint]
            to = "websecure"
            scheme = "https"

    [entryPoints.websecure]
    address = ":443"

[certificatesResolvers.lets-encrypt.acme]
    email = "evolentini@gmail.com"
    storage = "acme.json"
    [certificatesResolvers.lets-encrypt.acme.tlsChallenge]

[providers.docker]
    watch = true
    network = "proxy"

[providers.file]
    filename = "traefik_dynamic.toml"
